### ISSUE TITLE
Something wrong about SDO machine learning dataset V1

### ISSUE THREAD

**Issue by JinQiangShi** [SDOML/SDOML#1]
I have discovered that the file HMI_Bx_201308.tar is corrupted and cannot be extracted. I have repeatedly downloaded it from various sources (such as Stanford, AWS) and still cannot extract it. Therefore, I believe the file itself is corrupted, rather than a network issue. I kindly request that you provide me with a complete version of file HMI_Bx_201308.tar. Thank you very much.

**Comment by PaulJWright** [comment]
@kingbob8 do you have these locally?

**Comment by JinQiangShi** [comment]
> @kingbob8 do you have these locally?

Yes, I have downloaded all the HMI_Bx,HMI_By,HMI_Bz data from May 2010 to December 2018 locally, but the HMI_Bx data from August 2013 is corrupted and cannot be extracted. It’s hard to believe, but it's true, and I’ve downloaded it at least 8 times (at least 6 times from Stanford and 2 times from AWS). Therefore, I believe it might not be a network issue, but rather that the data itself is corrupted.

**Comment by PaulJWright** [comment]
> Yes, I have downloaded all the HMI_Bx,HMI_By,HMI_Bz data from May 2010 to December 2018 locally, but the HMI_Bx data from August 2013 is corrupted and cannot be extracted. It’s hard to believe, but it's true, and I’ve downloaded it at least 8 times (at least 6 times from Stanford and 2 times from AWS). Therefore, I believe it might not be a network issue, but rather that the data itself is corrupted.

I was asking my colleague if he has the file locally so we can update this for you

**Comment by kingbob8** [comment]
I believe I have a local copy. Let me check and come back to you!

**Comment by JinQiangShi** [comment]
> I believe I have a local copy. Let me check and come back to you!

Thank you very much for your help. Have you found the copy?

**Comment by kingbob8** [comment]
The hard drive is with one of my co-workers, who is on travel until Friday. I will update you as soon as he comes back.

**Comment by kingbob8** [comment]
The HMI_Bx_201308.tar file now can be downloaded from: https://drive.google.com/drive/folders/17gZn1BZaANgAZyeuKEdmmhOmfUJe6zF1?usp=sharing <https://drive.google.com/drive/folders/17gZn1BZaANgAZyeuKEdmmhOmfUJe6zF1?usp=sharing>. Thanks!
